web: python src/web/web.py instance/web.cfg
control30: python src/monitors/control.py src/monitors/config/control-30sec.yml
control1: python src/monitors/control.py src/monitors/config/control-1min.yml
control5: python src/monitors/control.py src/monitors/config/control-5min.yml
monitor_broker: python src/monitors/broker.py src/monitors/config/broker.yml
monitor_worker: python src/monitors/worker.py src/monitors/config/worker.yml
bridge: python src/bridge/bridge.py src/bridge/config/config.yml
action_broker: python src/actions/broker.py src/actions/config/broker.yml
actioner: python src/actions/actioner.py src/actions/config/actioner.yml
