From: CloudRoutes Notification <noreply@cloudrout.es>
To: {{ email }}
Subject: Success Detected - Failed to Re-add {{ ip }} to CloudFlare DNS for {{ domain }}

Hiya,

We noticed {{ ip }}:{{ port }} is back up. However, we ran into issues re-adding your IP to DNS. We suggest you validate your DNS records to ensure that they look the way you expect them to.

- CloudRoutes

https://cloudrout.es
https://twitter.com/cloudroutes

