From: CloudRoutes Notification <noreply@cloudrout.es>
To: {{ email }}
Subject: Failed Monitor - {{ name }}

Howdie,

This is an automated notification that the monitor {{ name }} has returned failed.

Just a heads up, we rate limit failure emails to a minimum of 15 minutes. You can decrease the frequency of failure emails by changing the frequency value of this reaction.

- CloudRoutes

https://cloudrout.es
https://twitter.com/cloudroutes
